[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
async-graphql = "4.0.9"
async-graphql-actix-web = "4.0.9"
env_logger = "0.9.0"
futures = "0.3.23"
actix-cors = "0.6.2"